function createHeader() {
    let header = document.createElement("header");
    header.innerHTML = '<a class="header__logo" href="index.html " title="Переход на главную страницу "> <img class="header__logo__image " src="images/icons/logo.svg " alt="YouTalk - подберем психолога под ваш запрос "> </a> <nav class="header__menu"> <div class="header__menu__btn pointer"></div> <ul class="d-flex-between">  <li class="header__menu__link "><a href="#">О нас</a></li>  <li class="header__menu__link "><a href="#">Тарифы</a></li>  <li class="header__menu__link "><a href="#">Для бизнеса</a></li>  <li class="header__menu__link "><a href="#">Психологам</a></li>  <li class="header__menu__link "><a href="#">Сертификат</a></li>  <li class="header__menu__link_drop-down "><a href=" ">Материалы</a></li>  <li class="header__menu__link "><a href="#">FAQ</a></li> </ul> </nav> <div class="header__btn d-flex-end"> <button class="header__btn__choose-psycho pointer">Подобрать психолога</button>';
    header.setAttribute("class", "d-flex-center");
    document.body.appendChild(header);
}

function createFooter() {
    let footer = document.createElement('footer');
    footer.innerHTML = '<section class="d-flex-between"> <div class="footer__info d-flex-between"> <ul>  <li class="footer__info__link"><a href="#">О нас</a></li>  <li class="footer__info__link"><a href="#">Тарифы</a></li>  <li class="footer__info__link"><a href="#">Для Бизнеса</a></li>  <li class="footer__info__link"><a href="#">Психологам</a></li>  <li class="footer__info__link"><a href="#">FAQ</a></li>  <li class="footer__info__link"><a href="#">Блог</a></li>  <li class="footer__info__link"><a href="#">Вебинары</a></li>  <li class="footer__info__link"><a href="#">Подкаст</a></li>  <li class="footer__info__link"><a href="#">Сертификат</a></li>  <li class="footer__info__link"><a href="#">Контакты</a></li> </ul> </div> <div class="footer__feedback"> <form action="">  <h4><strong>Одно письмо в неделю со свежими новостями и акциями</strong></h4>  <input class="footer__feedback__send-email" type="email" placeholder="Ваш E-mail">  <input type="submit" value="" class="footer__feedback__button"> </form> <p class="small-text footer__feedback__info">Подписываясь, я соглашаюсь на обработку персональных данных в соответствии с ФЗ РФ № 152-ФЗ «О персональных данных», а также с Политикой конфиденциальности</p> </div> <div class="footer__social-media"> <a href="#" title="Ссылка на анкету ученика"><img src="images/icons/SF_logo.svg" alt="Ссылка на анкету ученика"></a> <div class="footer__social-media__links d-flex-start">  <a href="#" title="Ссылка на ВКонтакте"><img src="images/icons/social/vk.svg" alt="Ссылка на ВКонтакте"></a>  <a href="#" title="Ссылка на Телеграм"><img src="images/icons/social/tg.svg" alt="Ссылка на Телеграм"></a>  <a href="#" title="Ссылка на Твиттер"><img src="images/icons/social/twitter.svg" alt="Ссылка на Твиттер"></a>  <a href="#" title="Ссылка на Яндекс-Дзен"><img src="images/icons/social/dzen.svg" alt="Ссылка на Яндекс-Дзен"></a> </div> </div> </section> <hr> <section> <p>@YouTalk, 2018 - 2022</p> <p>Юридические документы</p> <p>Способы оплаты</p> </section>';
    document.body.appendChild(footer);
}